/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProvingGroundRouteImport } from './routes/proving-ground'
import { Route as QuarryRouteImport } from './routes/quarry'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvingGroundRoute = ProvingGroundRouteImport.update({
  id: '/proving-ground',
  path: '/proving-ground',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarryRoute = QuarryRouteImport.update({
  id: '/quarry',
  path: '/quarry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/proving-ground': typeof ProvingGroundRoute
  '/quarry': typeof QuarryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rtc': typeof ApiRtcRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/proving-ground': typeof ProvingGroundRoute
  '/quarry': typeof QuarryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rtc': typeof ApiRtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/proving-ground': typeof ProvingGroundRoute
  '/quarry': typeof QuarryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rtc': typeof ApiRtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract'
    | '/editor'
    | '/login'
    | '/proving-ground'
    | '/quarry'
    | '/api/auth/$'
    | '/api/rtc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract'
    | '/editor'
    | '/login'
    | '/proving-ground'
    | '/quarry'
    | '/api/auth/$'
    | '/api/rtc'
  id:
    | '__root__'
    | '/'
    | '/contract'
    | '/editor'
    | '/login'
    | '/proving-ground'
    | '/quarry'
    | '/api/auth/$'
    | '/api/rtc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractRoute: typeof ContractRoute
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  ProvingGroundRoute: typeof ProvingGroundRoute
  QuarryRoute: typeof QuarryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRtcRoute: typeof ApiRtcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proving-ground': {
      id: '/proving-ground'
      path: '/proving-ground'
      fullPath: '/proving-ground'
      preLoaderRoute: typeof ProvingGroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarry': {
      id: '/quarry'
      path: '/quarry'
      fullPath: '/quarry'
      preLoaderRoute: typeof QuarryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractRoute: ContractRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  ProvingGroundRoute: ProvingGroundRoute,
  QuarryRoute: QuarryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRtcRoute: ApiRtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
