import type { HullBlueprint } from "./hull.ts";
import { hullBlueprintSchema } from "./hull.ts";
import { assertCatalogLaws } from "./rules.ts";
import { assertTreeLaws } from "./tree.ts";
import { assertArtilleryLaws } from "./artillery.ts";
import { EXPERT_HULLS } from "./catalog-expert.ts";
import { plate } from "./armor.ts";

/** Starter Light — US M2A4. Single manual ring. Sponsons are hull weapons. */
export const M2A4: HullBlueprint = {
  id: "m2a4",
  name: "Light Tank M2A4",
  shortName: "M2A4",
  class: "light",
  nation: "usa",
  lengthM: 4.43,
  widthM: 2.47,
  hullYawRateDegPerSec: 38,
  forwardSpeedMps: 12.5,
  defaultEngineNorm: 1,
  hp: 180,
  armor: {
    hullFront: plate(25),
    hullSide: plate(25),
    hullRear: plate(25),
    turretFront: plate(25),
    turretSide: plate(25),
    turretRear: plate(25),
  },
  notes:
    "Assumed traverse 22°/s. M20 ±10° is mountTraverseDeg on the 37 mm, not a second ring. Armor/pen assumed 100 m AP. AA pintle deferred. M2A2/A3 twin turret deferred.",
  turrets: [
    {
      id: "m2a4-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 22,
      drive: "manual",
      offsetForwardM: 0.2,
      offsetRightM: 0,
      ringRadiusM: 0.59,
      defaultWeaponId: "m2a4-m5",
      notes: "Two-man turret, no basket. Commander loads.",
    },
  ],
  weapons: [
    {
      id: "m2a4-m5",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "m2a4-main",
      caliberMm: 37,
      penMm: 48,
      damageHp: 55,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -6,
      elevationMaxDeg: 19,
      mountTraverseDeg: 10,
      slavedToWeaponId: null,
      offsetForwardM: 0.55,
      offsetRightM: 0,
      notes: "37 mm M5 on M20. Leftover ±10° if the ring jams.",
    },
    {
      id: "m2a4-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "m2a4-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -6,
      elevationMaxDeg: 19,
      mountTraverseDeg: 0,
      slavedToWeaponId: "m2a4-m5",
      offsetForwardM: 0.5,
      offsetRightM: 0.12,
      notes: "Slaved to the 37 mm.",
    },
    {
      id: "m2a4-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -17,
      arcMaxDeg: 14,
      elevationMinDeg: -14,
      elevationMaxDeg: 24,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.9,
      offsetRightM: 0.45,
      notes: "Assistant driver. Not a turret.",
    },
    {
      id: "m2a4-sponson-l",
      kind: "sponson_fixed",
      mount: "hull_fixed",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: 0,
      arcMaxDeg: 0,
      elevationMinDeg: 0,
      elevationMaxDeg: 0,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.1,
      offsetRightM: -1.05,
      notes: "Fixed forward. Not a T-28 sub-turret.",
    },
    {
      id: "m2a4-sponson-r",
      kind: "sponson_fixed",
      mount: "hull_fixed",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: 0,
      arcMaxDeg: 0,
      elevationMinDeg: 0,
      elevationMaxDeg: 0,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.1,
      offsetRightM: 1.05,
      notes: "Fixed forward. Not a T-28 sub-turret.",
    },
  ],
};

/** USA T2 — Light Tank M3 (late). One manual ring. Sponsons still hull guns. */
export const M3_STUART: HullBlueprint = {
  id: "m3-stuart",
  name: "Light Tank M3",
  shortName: "M3",
  class: "light",
  nation: "usa",
  lengthM: 4.53,
  widthM: 2.24,
  hullYawRateDegPerSec: 42,
  forwardSpeedMps: 16,
  defaultEngineNorm: 1,
  hp: 220,
  armor: {
    hullFront: plate(38),
    hullSide: plate(25),
    hullRear: plate(25),
    turretFront: plate(38),
    turretSide: plate(32),
    turretRear: plate(32),
  },
  notes:
    "Late M3: 37 mm M6, manual 360 ring. Sponson MGs are hull_fixed. AA M20 pintle deferred. M3A1 hydraulic 24°/s + gyro + no sponsons deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "m3-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 20,
      drive: "manual",
      offsetForwardM: 0.15,
      offsetRightM: 0,
      ringRadiusM: 0.59,
      defaultWeaponId: "m3-m6",
      notes: "Two-man turret, no basket. Commander loads. M3A1 basket deferred.",
    },
  ],
  weapons: [
    {
      id: "m3-m6",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "m3-main",
      caliberMm: 37,
      penMm: 56,
      damageHp: 55,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 0.6,
      offsetRightM: 0,
      notes: "37 mm M6. Leftover 0 — not an M20.",
    },
    {
      id: "m3-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "m3-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: "m3-m6",
      offsetForwardM: 0.55,
      offsetRightM: 0.12,
      notes: "Slaved to the 37 mm.",
    },
    {
      id: "m3-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -17,
      arcMaxDeg: 14,
      elevationMinDeg: -14,
      elevationMaxDeg: 24,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.95,
      offsetRightM: 0.42,
      notes: "M13 ball. Assistant driver. Not a turret.",
    },
    {
      id: "m3-sponson-l",
      kind: "sponson_fixed",
      mount: "hull_fixed",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: 0,
      arcMaxDeg: 0,
      elevationMinDeg: 0,
      elevationMaxDeg: 0,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.15,
      offsetRightM: -0.95,
      notes: "Fixed forward. Not a ring.",
    },
    {
      id: "m3-sponson-r",
      kind: "sponson_fixed",
      mount: "hull_fixed",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: 0,
      arcMaxDeg: 0,
      elevationMinDeg: 0,
      elevationMaxDeg: 0,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.15,
      offsetRightM: 0.95,
      notes: "Fixed forward. Not a ring.",
    },
  ],
};

/** USA T3 — Light Tank M5. One hydraulic ring. No sponsons. */
export const M5_STUART: HullBlueprint = {
  id: "m5-stuart",
  name: "Light Tank M5",
  shortName: "M5",
  class: "light",
  nation: "usa",
  lengthM: 4.34,
  widthM: 2.24,
  hullYawRateDegPerSec: 44,
  forwardSpeedMps: 16.1,
  defaultEngineNorm: 1,
  hp: 250,
  armor: {
    hullFront: plate(29, 48),
    hullSide: plate(25),
    hullRear: plate(25),
    turretFront: plate(38, 10),
    turretSide: plate(32),
    turretRear: plate(32),
  },
  notes:
    "M5: twin Cadillac, 37 mm M6, hydraulic 24°/s 360 ring. No sponson MGs. Bow MG hull_ball. Gyro + M5A1 bustle turret deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "m5-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 24,
      drive: "hydraulic",
      offsetForwardM: 0.12,
      offsetRightM: 0,
      ringRadiusM: 0.59,
      defaultWeaponId: "m5-m6",
      notes: "Oilgear hydraulic 24°/s. Manual backup. Same RING LAW as Tiger, faster.",
    },
  ],
  weapons: [
    {
      id: "m5-m6",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "m5-main",
      caliberMm: 37,
      penMm: 56,
      damageHp: 55,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 0.6,
      offsetRightM: 0,
      notes: "37 mm M6. Leftover 0.",
    },
    {
      id: "m5-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "m5-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: "m5-m6",
      offsetForwardM: 0.55,
      offsetRightM: 0.12,
      notes: "Slaved to the 37 mm.",
    },
    {
      id: "m5-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -17,
      arcMaxDeg: 14,
      elevationMinDeg: -14,
      elevationMaxDeg: 24,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.9,
      offsetRightM: 0.42,
      notes: "M13 ball. Assistant driver. Not a turret. No sponsons on M5.",
    },
  ],
};

/** USA T4 — Light Tank M24 Chaffee. One hydraulic ring. 75 mm M6. Sloped glacis. */
export const M24_CHAFFEE: HullBlueprint = {
  id: "m24-chaffee",
  name: "Light Tank M24",
  shortName: "M24",
  class: "light",
  nation: "usa",
  lengthM: 5.03,
  widthM: 2.84,
  hullYawRateDegPerSec: 40,
  forwardSpeedMps: 15.6,
  defaultEngineNorm: 1,
  hp: 320,
  armor: {
    hullFront: plate(25, 60),
    hullSide: plate(25),
    hullRear: plate(19),
    turretFront: plate(38),
    turretSide: plate(25),
    turretRear: plate(25),
  },
  notes:
    "M24: 75 mm M6 (Sherman M3 ballistics), hydraulic 24°/s 360 ring, three-man turret. Glacis 25 mm @ 60°. Bow MG hull_ball. Pintle .50 + 2-in mortar deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "m24-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 24,
      drive: "hydraulic",
      offsetForwardM: 0.1,
      offsetRightM: 0,
      ringRadiusM: 0.76,
      defaultWeaponId: "m24-m6",
      notes: "Hydraulic 24°/s. Hand backup. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "m24-m6",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "m24-main",
      caliberMm: 75,
      penMm: 109,
      damageHp: 110,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 15,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 0.9,
      offsetRightM: 0,
      notes: "75 mm M6 in M64. Same ammo as Sherman M3. Assumed M61 ~100 m.",
    },
    {
      id: "m24-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "m24-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 15,
      mountTraverseDeg: 0,
      slavedToWeaponId: "m24-m6",
      offsetForwardM: 0.85,
      offsetRightM: 0.14,
      notes: "M1919A4 slaved to the 75 mm.",
    },
    {
      id: "m24-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -17,
      arcMaxDeg: 14,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.1,
      offsetRightM: 0.4,
      notes: "Bow M1919. Assistant driver. Not a turret.",
    },
  ],
};

/** USA T5 — Medium Tank M4A3(75)W. One hydraulic ring. 75 mm M3. Sloped glacis. */
export const M4A3_SHERMAN: HullBlueprint = {
  id: "m4a3-sherman",
  name: "Medium Tank M4A3",
  shortName: "M4A3",
  class: "medium",
  nation: "usa",
  lengthM: 6.27,
  widthM: 2.67,
  hullYawRateDegPerSec: 28,
  forwardSpeedMps: 11.6,
  defaultEngineNorm: 1,
  hp: 560,
  armor: {
    hullFront: plate(64, 47),
    hullSide: plate(38),
    hullRear: plate(38),
    turretFront: plate(76, 30),
    turretSide: plate(51),
    turretRear: plate(51),
  },
  notes:
    "M4A3(75)W: Ford GAA, 75 mm M3, Oilgear hydraulic 24°/s. Glacis 64 mm @ 47°. Bow MG hull_ball. Wet stowage + 76W / Easy Eight deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "m4a3-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 24,
      drive: "hydraulic",
      offsetForwardM: 0.05,
      offsetRightM: 0,
      ringRadiusM: 0.88,
      defaultWeaponId: "m4a3-m3",
      notes: "Oilgear hydraulic 24°/s. Three-man turret. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "m4a3-m3",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "m4a3-main",
      caliberMm: 75,
      penMm: 109,
      damageHp: 110,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.2,
      offsetRightM: 0,
      notes: "75 mm M3 L/40. Same ammo as M24 M6. Assumed M61 ~100 m.",
    },
    {
      id: "m4a3-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "m4a3-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -10,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: "m4a3-m3",
      offsetForwardM: 1.1,
      offsetRightM: 0.16,
      notes: "M1919A4 slaved to the 75 mm.",
    },
    {
      id: "m4a3-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -20,
      arcMaxDeg: 20,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.3,
      offsetRightM: 0.45,
      notes: "Bow M1919. Assistant driver. Not a turret.",
    },
  ],
};

/** Starter Medium — Soviet T-28. Three rings. */
export const T28: HullBlueprint = {
  id: "t-28",
  name: "T-28",
  shortName: "T-28",
  class: "medium",
  nation: "ussr",
  lengthM: 7.44,
  widthM: 2.87,
  hullYawRateDegPerSec: 22,
  forwardSpeedMps: 10.3,
  defaultEngineNorm: 1,
  hp: 320,
  armor: {
    hullFront: plate(30),
    hullSide: plate(20),
    hullRear: plate(20),
    turretFront: plate(20),
    turretSide: plate(20),
    turretRear: plate(20),
  },
  notes:
    "Three independent rings. Small-turret arc frozen at 165° stop-to-stop. Rear/AA DT deferred. Electric main vs manual MG rings. Armor/pen assumed 100 m AP. KT-28 does not pen Tiger front.",
  turrets: [
    {
      id: "t28-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 14,
      drive: "electric",
      offsetForwardM: 0.35,
      offsetRightM: 0,
      ringRadiusM: 0.85,
      defaultWeaponId: "t28-kt28",
      notes: "Raised superstructure. Fires over the MG rings.",
    },
    {
      id: "t28-mg-port",
      role: "mg_port",
      arcMinDeg: -165,
      arcMaxDeg: 0,
      wrap: false,
      traverseRateDegPerSec: 28,
      drive: "manual",
      offsetForwardM: 2.15,
      offsetRightM: -0.72,
      ringRadiusM: 0.38,
      defaultWeaponId: "t28-dt-port",
      notes: "Dedicated gunner. Stops at driver box / hull wall.",
    },
    {
      id: "t28-mg-starboard",
      role: "mg_starboard",
      arcMinDeg: 0,
      arcMaxDeg: 165,
      wrap: false,
      traverseRateDegPerSec: 28,
      drive: "manual",
      offsetForwardM: 2.15,
      offsetRightM: 0.72,
      ringRadiusM: 0.38,
      defaultWeaponId: "t28-dt-starboard",
      notes: "Dedicated gunner. Stops at driver box / hull wall.",
    },
  ],
  weapons: [
    {
      id: "t28-kt28",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "t28-main",
      caliberMm: 76.2,
      penMm: 34,
      damageHp: 110,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 0.9,
      offsetRightM: 0,
      notes: "KT-28 76.2 mm. L-10 later — not a second card.",
    },
    {
      id: "t28-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "t28-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: "t28-kt28",
      offsetForwardM: 0.85,
      offsetRightM: 0.18,
      notes: "Slaved. Historical ±30° ball is not a ring.",
    },
    {
      id: "t28-dt-port",
      kind: "mg",
      mount: "turret_ring",
      turretId: "t28-mg-port",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -165,
      arcMaxDeg: 0,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.35,
      offsetRightM: -0.72,
      notes: "Independent MG on a ring. Auto-tracks in arc.",
    },
    {
      id: "t28-dt-starboard",
      kind: "mg",
      mount: "turret_ring",
      turretId: "t28-mg-starboard",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: 0,
      arcMaxDeg: 165,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.35,
      offsetRightM: 0.72,
      notes: "Independent MG on a ring. Auto-tracks in arc.",
    },
  ],
};

/** USSR T2 — T-28E. Same three rings. Applique plates, same KT-28. */
export const T28E: HullBlueprint = {
  id: "t-28e",
  name: "T-28E",
  shortName: "T-28E",
  class: "medium",
  nation: "ussr",
  lengthM: 7.44,
  widthM: 2.87,
  hullYawRateDegPerSec: 16,
  forwardSpeedMps: 6.4,
  defaultEngineNorm: 1,
  hp: 400,
  armor: {
    hullFront: plate(50),
    hullSide: plate(40),
    hullRear: plate(30),
    turretFront: plate(50),
    turretSide: plate(40),
    turretRear: plate(30),
  },
  notes:
    "Ekranirovki applique. Same three rings and 165° MG stops. KT-28 kept — L-10 is not this card. Speed 23 km/h. Armor assumed 20 mm screens on the T-28 plates. M3 56 pens the front; M2 48 may bounce.",
  turrets: [
    {
      id: "t28e-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 14,
      drive: "electric",
      offsetForwardM: 0.35,
      offsetRightM: 0,
      ringRadiusM: 0.85,
      defaultWeaponId: "t28e-kt28",
      notes: "Same raised ring. Screens on the face.",
    },
    {
      id: "t28e-mg-port",
      role: "mg_port",
      arcMinDeg: -165,
      arcMaxDeg: 0,
      wrap: false,
      traverseRateDegPerSec: 28,
      drive: "manual",
      offsetForwardM: 2.15,
      offsetRightM: -0.72,
      ringRadiusM: 0.38,
      defaultWeaponId: "t28e-dt-port",
      notes: "Same 165° stop. Applique on the MG ring too.",
    },
    {
      id: "t28e-mg-starboard",
      role: "mg_starboard",
      arcMinDeg: 0,
      arcMaxDeg: 165,
      wrap: false,
      traverseRateDegPerSec: 28,
      drive: "manual",
      offsetForwardM: 2.15,
      offsetRightM: 0.72,
      ringRadiusM: 0.38,
      defaultWeaponId: "t28e-dt-starboard",
      notes: "Same 165° stop. Applique on the MG ring too.",
    },
  ],
  weapons: [
    {
      id: "t28e-kt28",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "t28e-main",
      caliberMm: 76.2,
      penMm: 34,
      damageHp: 110,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 0.9,
      offsetRightM: 0,
      notes: "KT-28. L-10 deferred.",
    },
    {
      id: "t28e-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "t28e-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: "t28e-kt28",
      offsetForwardM: 0.85,
      offsetRightM: 0.18,
      notes: "Slaved.",
    },
    {
      id: "t28e-dt-port",
      kind: "mg",
      mount: "turret_ring",
      turretId: "t28e-mg-port",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -165,
      arcMaxDeg: 0,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.35,
      offsetRightM: -0.72,
      notes: "Independent MG on a ring.",
    },
    {
      id: "t28e-dt-starboard",
      kind: "mg",
      mount: "turret_ring",
      turretId: "t28e-mg-starboard",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: 0,
      arcMaxDeg: 165,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.35,
      offsetRightM: 0.72,
      notes: "Independent MG on a ring.",
    },
  ],
};

/** USSR T3 — T-34 Model 1941. One electric ring. F-34. Sloped glacis. */
export const T34: HullBlueprint = {
  id: "t-34",
  name: "T-34",
  shortName: "T-34",
  class: "medium",
  nation: "ussr",
  lengthM: 6.68,
  widthM: 3.0,
  hullYawRateDegPerSec: 32,
  forwardSpeedMps: 14.7,
  defaultEngineNorm: 1,
  hp: 420,
  armor: {
    hullFront: plate(45, 60),
    hullSide: plate(40, 40),
    hullRear: plate(40),
    turretFront: plate(45),
    turretSide: plate(45, 30),
    turretRear: plate(45),
  },
  notes:
    "Model 1941: 76.2 mm F-34, electric 360 ring, two-man turret. Glacis 45 mm @ 60°. DT bow is hull_ball. T-34-85 three-man turret deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "t34-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 26,
      drive: "electric",
      offsetForwardM: 0.35,
      offsetRightM: 0,
      ringRadiusM: 0.71,
      defaultWeaponId: "t34-f34",
      notes: "Electric traverse ~26°/s. Commander is also gunner. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "t34-f34",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "t34-main",
      caliberMm: 76.2,
      penMm: 86,
      damageHp: 115,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.1,
      offsetRightM: 0,
      notes: "76.2 mm F-34 L/42. Assumed BR-350A ~100 m.",
    },
    {
      id: "t34-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "t34-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 25,
      mountTraverseDeg: 0,
      slavedToWeaponId: "t34-f34",
      offsetForwardM: 1.0,
      offsetRightM: 0.15,
      notes: "DT slaved to F-34.",
    },
    {
      id: "t34-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -12,
      arcMaxDeg: 12,
      elevationMinDeg: -6,
      elevationMaxDeg: 16,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.4,
      offsetRightM: 0.35,
      notes: "Hull DT. Radio operator. Not a turret.",
    },
  ],
};

/** USSR T4 — T-34-85 Model 1944. One electric ring. ZiS-S-53. Same glacis, thicker turret. */
export const T34_85: HullBlueprint = {
  id: "t-34-85",
  name: "T-34-85",
  shortName: "T-34-85",
  class: "medium",
  nation: "ussr",
  lengthM: 8.1,
  widthM: 3.0,
  hullYawRateDegPerSec: 30,
  forwardSpeedMps: 13.9,
  defaultEngineNorm: 1,
  hp: 520,
  armor: {
    hullFront: plate(45, 60),
    hullSide: plate(45),
    hullRear: plate(45),
    turretFront: plate(90),
    turretSide: plate(75),
    turretRear: plate(52),
  },
  notes:
    "Model 1944: 85 mm ZiS-S-53, electric 360 ring, three-man turret. Glacis still 45 mm @ 60°. DT bow hull_ball. D-5T early run deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "t3485-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 20,
      drive: "electric",
      offsetForwardM: 0.2,
      offsetRightM: 0,
      ringRadiusM: 0.8,
      defaultWeaponId: "t3485-zis",
      notes: "Electric ~20°/s. Commander no longer guns. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "t3485-zis",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "t3485-main",
      caliberMm: 85,
      penMm: 125,
      damageHp: 160,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 22,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.2,
      offsetRightM: 0,
      notes: "85 mm ZiS-S-53. Assumed BR-365 ~100 m.",
    },
    {
      id: "t3485-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "t3485-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 22,
      mountTraverseDeg: 0,
      slavedToWeaponId: "t3485-zis",
      offsetForwardM: 1.1,
      offsetRightM: 0.16,
      notes: "DT slaved to ZiS-S-53.",
    },
    {
      id: "t3485-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -12,
      arcMaxDeg: 12,
      elevationMinDeg: -6,
      elevationMaxDeg: 16,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.4,
      offsetRightM: 0.35,
      notes: "Hull DT. Radio operator. Not a turret.",
    },
  ],
};

/** USSR T5 — T-44. One electric ring. Same 85 mm. 90 mm glacis @ 60°. No bow MG. */
export const T44: HullBlueprint = {
  id: "t-44",
  name: "T-44",
  shortName: "T-44",
  class: "medium",
  nation: "ussr",
  lengthM: 7.65,
  widthM: 3.25,
  hullYawRateDegPerSec: 30,
  forwardSpeedMps: 16.8,
  defaultEngineNorm: 1,
  hp: 640,
  armor: {
    hullFront: plate(90, 60),
    hullSide: plate(75),
    hullRear: plate(45),
    turretFront: plate(120),
    turretSide: plate(90),
    turretRear: plate(75),
  },
  notes:
    "T-44A: 85 mm ZiS-S-53, electric 360 ring, torsion-bar hull. Glacis 90 mm @ 60°. No hull MG. T-44-100 deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "t44-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 20,
      drive: "electric",
      offsetForwardM: 0.15,
      offsetRightM: 0,
      ringRadiusM: 0.8,
      defaultWeaponId: "t44-zis",
      notes: "Electric ~20°/s. Three-man. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "t44-zis",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "t44-main",
      caliberMm: 85,
      penMm: 125,
      damageHp: 160,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.15,
      offsetRightM: 0,
      notes: "85 mm ZiS-S-53. Same as T-34-85.",
    },
    {
      id: "t44-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "t44-main",
      caliberMm: 7.62,
      penMm: 12,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -5,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: "t44-zis",
      offsetForwardM: 1.05,
      offsetRightM: 0.16,
      notes: "DT slaved to ZiS-S-53.",
    },
  ],
};

/** Starter Heavy — Tiger I Ausf. E. One hydraulic ring. */
export const TIGER_I: HullBlueprint = {
  id: "tiger-i",
  name: "Pz.Kpfw. VI Tiger Ausf. E",
  shortName: "Tiger I",
  class: "heavy",
  nation: "germany",
  lengthM: 6.316,
  widthM: 3.7,
  hullYawRateDegPerSec: 16,
  forwardSpeedMps: 10.5,
  defaultEngineNorm: 0.4,
  hp: 850,
  armor: {
    hullFront: plate(100),
    hullSide: plate(80),
    hullRear: plate(80),
    turretFront: plate(100),
    turretSide: plate(80),
    turretRear: plate(80),
  },
  notes:
    "Hydraulic traverseRate is idle band (~6°/s). Scales with engineNorm. Bow MG is hull_ball. Cupola is a module, not a turret. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "tiger-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 6,
      drive: "hydraulic",
      offsetForwardM: 0.1,
      offsetRightM: 0,
      ringRadiusM: 0.91,
      defaultWeaponId: "tiger-kwk36",
      notes: "Boehringer-Sturm L4. Hand backup when engine or ring fails.",
    },
  ],
  weapons: [
    {
      id: "tiger-kwk36",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "tiger-main",
      caliberMm: 88,
      penMm: 132,
      damageHp: 240,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -6.5,
      elevationMaxDeg: 17,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.4,
      offsetRightM: 0,
      notes: "8.8 cm KwK 36 L/56.",
    },
    {
      id: "tiger-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "tiger-main",
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -6.5,
      elevationMaxDeg: 17,
      mountTraverseDeg: 0,
      slavedToWeaponId: "tiger-kwk36",
      offsetForwardM: 1.3,
      offsetRightM: 0.2,
      notes: "Slaved to the 88.",
    },
    {
      id: "tiger-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -15,
      arcMaxDeg: 15,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.7,
      offsetRightM: 0.55,
      notes: "Radio operator. Not a turret.",
    },
  ],
};

/** Germany T2 — Tiger II Ausf. B, production turret. One hydraulic ring. */
export const TIGER_II: HullBlueprint = {
  id: "tiger-ii",
  name: "Pz.Kpfw. Tiger Ausf. B",
  shortName: "Tiger II",
  class: "heavy",
  nation: "germany",
  lengthM: 7.38,
  widthM: 3.76,
  hullYawRateDegPerSec: 12,
  forwardSpeedMps: 8,
  defaultEngineNorm: 0.4,
  hp: 1100,
  armor: {
    hullFront: plate(150),
    hullSide: plate(80),
    hullRear: plate(80),
    turretFront: plate(180),
    turretSide: plate(80),
    turretRear: plate(80),
  },
  notes:
    "Production (Henschel) turret. Boehringer-Sturm L4S hydraulic, idle 5°/s, scales with engine. Bow MG is hull_ball. Porsche turret / Jagdtiger deferred. Armor/pen assumed 100 m AP. KwK 43 202 mm; Tiger I 132 does not pen this face.",
  turrets: [
    {
      id: "tiger-ii-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 5,
      drive: "hydraulic",
      offsetForwardM: 0.05,
      offsetRightM: 0,
      ringRadiusM: 0.95,
      defaultWeaponId: "tiger-ii-kwk43",
      notes: "L4S. Hand backup when engine or ring fails.",
    },
  ],
  weapons: [
    {
      id: "tiger-ii-kwk43",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "tiger-ii-main",
      caliberMm: 88,
      penMm: 202,
      damageHp: 280,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -8,
      elevationMaxDeg: 15,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.8,
      offsetRightM: 0,
      notes: "8.8 cm KwK 43 L/71. Leftover 0.",
    },
    {
      id: "tiger-ii-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "tiger-ii-main",
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -8,
      elevationMaxDeg: 15,
      mountTraverseDeg: 0,
      slavedToWeaponId: "tiger-ii-kwk43",
      offsetForwardM: 1.7,
      offsetRightM: 0.2,
      notes: "Slaved to the L/71.",
    },
    {
      id: "tiger-ii-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -15,
      arcMaxDeg: 15,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 3.1,
      offsetRightM: 0.55,
      notes: "Radio operator. Not a turret.",
    },
  ],
};

/** Germany T3 — Panther Ausf. A. One hydraulic ring. KwK 42. Sloped glacis. */
export const PANTHER: HullBlueprint = {
  id: "panther",
  name: "Pz.Kpfw. V Panther Ausf. A",
  shortName: "Panther",
  class: "medium",
  nation: "germany",
  lengthM: 6.87,
  widthM: 3.27,
  hullYawRateDegPerSec: 24,
  forwardSpeedMps: 12.8,
  defaultEngineNorm: 1,
  hp: 750,
  armor: {
    hullFront: plate(80, 55),
    hullSide: plate(40),
    hullRear: plate(40),
    turretFront: plate(100),
    turretSide: plate(45),
    turretRear: plate(45),
  },
  notes:
    "Ausf. A: 7.5 cm KwK 42 L/70, Boehringer-Sturm L4 hydraulic 6°/s. Glacis 80 mm @ 55°. Bow MG hull_ball. High-gear 19°/s + Ausf. G side bump deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "panther-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 6,
      drive: "hydraulic",
      offsetForwardM: 0.2,
      offsetRightM: 0,
      ringRadiusM: 0.82,
      defaultWeaponId: "panther-kwk42",
      notes: "L4 hydraulic. Idle 6°/s, scales with engine. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "panther-kwk42",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "panther-main",
      caliberMm: 75,
      penMm: 138,
      damageHp: 135,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -8,
      elevationMaxDeg: 18,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.6,
      offsetRightM: 0,
      notes: "7.5 cm KwK 42 L/70. Assumed Pzgr 39/42 ~100 m.",
    },
    {
      id: "panther-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "panther-main",
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -8,
      elevationMaxDeg: 18,
      mountTraverseDeg: 0,
      slavedToWeaponId: "panther-kwk42",
      offsetForwardM: 1.5,
      offsetRightM: 0.15,
      notes: "MG 34 slaved to KwK 42.",
    },
    {
      id: "panther-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -15,
      arcMaxDeg: 15,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.6,
      offsetRightM: 0.5,
      notes: "Radio operator. Not a turret.",
    },
  ],
};

/** Germany T4 — Panther Ausf. G. Same KwK 42. 50 mm sides. */
export const PANTHER_G: HullBlueprint = {
  id: "panther-g",
  name: "Pz.Kpfw. V Panther Ausf. G",
  shortName: "Panther G",
  class: "medium",
  nation: "germany",
  lengthM: 6.87,
  widthM: 3.27,
  hullYawRateDegPerSec: 22,
  forwardSpeedMps: 12.5,
  defaultEngineNorm: 1,
  hp: 780,
  armor: {
    hullFront: plate(80, 55),
    hullSide: plate(50, 30),
    hullRear: plate(40),
    turretFront: plate(100),
    turretSide: plate(45),
    turretRear: plate(45),
  },
  notes:
    "Ausf. G: same 7.5 cm KwK 42 L/70, L4 hydraulic 6°/s. Upper sides 50 mm @ 30°. Glacis still 80 @ 55°. Chin mantlet deferred. Armor/pen assumed 100 m AP.",
  turrets: [
    {
      id: "panther-g-main",
      role: "main",
      arcMinDeg: -180,
      arcMaxDeg: 180,
      wrap: true,
      traverseRateDegPerSec: 6,
      drive: "hydraulic",
      offsetForwardM: 0.2,
      offsetRightM: 0,
      ringRadiusM: 0.82,
      defaultWeaponId: "panther-g-kwk42",
      notes: "Same L4 as Ausf. A. Leftover 0.",
    },
  ],
  weapons: [
    {
      id: "panther-g-kwk42",
      kind: "main_gun",
      mount: "turret_ring",
      turretId: "panther-g-main",
      caliberMm: 75,
      penMm: 138,
      damageHp: 135,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -8,
      elevationMaxDeg: 18,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 1.6,
      offsetRightM: 0,
      notes: "7.5 cm KwK 42 L/70. Same as Ausf. A.",
    },
    {
      id: "panther-g-coax",
      kind: "coax",
      mount: "turret_ring",
      turretId: "panther-g-main",
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -180,
      arcMaxDeg: 180,
      elevationMinDeg: -8,
      elevationMaxDeg: 18,
      mountTraverseDeg: 0,
      slavedToWeaponId: "panther-g-kwk42",
      offsetForwardM: 1.5,
      offsetRightM: 0.15,
      notes: "MG 34 slaved to KwK 42.",
    },
    {
      id: "panther-g-bow",
      kind: "bow_mg",
      mount: "hull_ball",
      turretId: null,
      caliberMm: 7.92,
      penMm: 13,
      damageHp: 8,
      arcMinDeg: -15,
      arcMaxDeg: 15,
      elevationMinDeg: -10,
      elevationMaxDeg: 20,
      mountTraverseDeg: 0,
      slavedToWeaponId: null,
      offsetForwardM: 2.6,
      offsetRightM: 0.5,
      notes: "Radio operator. Not a turret.",
    },
  ],
};

export const STARTER_HULLS: HullBlueprint[] = [M2A4, T28, TIGER_I];
export const CATALOG_HULLS: HullBlueprint[] = [
  M2A4,
  M3_STUART,
  M5_STUART,
  M24_CHAFFEE,
  M4A3_SHERMAN,
  T28,
  T28E,
  T34,
  T34_85,
  T44,
  TIGER_I,
  TIGER_II,
  PANTHER,
  PANTHER_G,
  ...EXPERT_HULLS,
];

export function hullById(id: string): HullBlueprint | undefined {
  return CATALOG_HULLS.find((h) => h.id === id);
}

export function parseAndAssert(bp: HullBlueprint): HullBlueprint {
  const parsed = hullBlueprintSchema.parse(bp);
  const errors = assertCatalogLaws(parsed);
  if (errors.length) {
    throw new Error(errors.join("\n"));
  }
  return parsed;
}

export function validateStarterCatalog(): string[] {
  const hullErrors = CATALOG_HULLS.flatMap((bp) => {
    const parsed = hullBlueprintSchema.safeParse(bp);
    if (!parsed.success) {
      return [`${bp.id}: zod ${parsed.error.message}`];
    }
    return assertCatalogLaws(parsed.data);
  });
  return [...hullErrors, ...assertTreeLaws(CATALOG_HULLS), ...assertArtilleryLaws(CATALOG_HULLS)];
}
