export type IntroCue = {
  kind: "sfx" | "line";
  text: string;
};

export const INTRO_BRIEF = {
  id: "intro",
  src: "/audio/intro-briefing.mp3",
  title: "Garage briefing",
  cues: [
    { kind: "sfx", text: "metallic clanging in the distance" },
    { kind: "sfx", text: "grumbles" },
    { kind: "line", text: "Ah. You are awake." },
    { kind: "line", text: "Good." },
    { kind: "line", text: "For moment I think perhaps you are dead." },
    { kind: "line", text: "This would be inconvenient. I already filled out paperwork." },
    { kind: "sfx", text: "chuckles" },
    { kind: "line", text: "Welcome to **RING LAW**." },
    { kind: "line", text: "This is garage. This is range. This is also place where very expensive machines become very expensive holes in ground." },
    { kind: "line", text: "I am mechanic." },
    { kind: "line", text: "My job is to keep tank running." },
    { kind: "line", text: "Your job is to make my job difficult." },
    { kind: "line", text: "We understand each other." },
    { kind: "sfx", text: "clears throat" },
    { kind: "line", text: "First — choose your machine." },
    { kind: "line", text: "American. German. Soviet." },
    { kind: "line", text: "Three nations. Three engineering philosophies." },
    { kind: "line", text: "American tank comes with manual." },
    { kind: "line", text: "German tank comes with manual for manual." },
    { kind: "line", text: "Soviet tank comes with hammer." },
    { kind: "sfx", text: "proudly" },
    { kind: "line", text: "Hammer has never required software update." },
    { kind: "line", text: "You begin with starter machines. Fight battles, earn **experience and silver**, research your way through the tank trees, improve your equipment, and move into heavier, faster, meaner vehicles." },
    { kind: "line", text: "The **Fit** section is where you research upgrades." },
    { kind: "line", text: "**Info** tells you what strange steel animal you have selected — and you can listen to its garage briefing." },
    { kind: "line", text: "**Record** keeps track of what you have accomplished." },
    { kind: "line", text: "**Board** shows whether anyone else has accomplished more." },
    { kind: "sfx", text: "beat" },
    { kind: "line", text: "If yes... unfortunate." },
    { kind: "line", text: "Shoot them." },
    { kind: "line", text: "Now, maps." },
    { kind: "line", text: "You have official battlefields, different terrain, different cover, different weather." },
    { kind: "line", text: "Weather can make spotting harder." },
    { kind: "line", text: "It does not make armor thinner." },
    { kind: "line", text: "I have checked." },
    { kind: "line", text: "Several times." },
    { kind: "line", text: "There are also custom maps, because apparently giving tank commanders artillery was not enough power, so now we let them design geography." },
    { kind: "line", text: "There is a **Level Editor** if you wish to build your own battlefield." },
    { kind: "line", text: "Snow. Desert. Jungle. Forest. Urban." },
    { kind: "line", text: "Rivers, bridges, fords, buildings, vegetation, destructible cover..." },
    { kind: "line", text: "You create it." },
    { kind: "line", text: "Then drive seventy tons through it and discover what you did wrong." },
    { kind: "line", text: "This is called engineering." },
    { kind: "sfx", text: "excited" },
    { kind: "line", text: "Now! Driving." },
    { kind: "line", text: "**W and S** control throttle." },
    { kind: "line", text: "**A and D** turn hull." },
    { kind: "line", text: "Use the **mouse to aim**." },
    { kind: "line", text: "Click to fire." },
    { kind: "line", text: "Simple!" },
    { kind: "line", text: "Until other tank also fires." },
    { kind: "line", text: "Then suddenly very complicated." },
    { kind: "sfx", text: "chuckles" },
    { kind: "line", text: "Press **Q** to cycle ammunition." },
    { kind: "line", text: "You have **A.P.**, **A.P.C.R.**, and **H.E.**" },
    { kind: "line", text: "Different shells for different problems." },
    { kind: "line", text: "Do not use same answer for every target." },
    { kind: "line", text: "This is tank combat, not internet discussion." },
    { kind: "line", text: "Press **G** for lob or artillery fire when your vehicle supports it." },
    { kind: "line", text: "Place your reticle where you wish unpleasantness to arrive..." },
    { kind: "line", text: "and send package." },
    { kind: "line", text: "Delivery time varies." },
    { kind: "line", text: "Customer satisfaction is usually terrible." },
    { kind: "line", text: "If your tank becomes damaged, **R** uses a repair kit." },
    { kind: "line", text: "If you need eyes beyond your own, **T** calls aerial reconnaissance." },
    { kind: "line", text: "Very useful." },
    { kind: "line", text: "Enemy cannot shoot what he cannot see." },
    { kind: "line", text: "Well..." },
    { kind: "sfx", text: "hesitates" },
    { kind: "line", text: "He can." },
    { kind: "line", text: "But then he is guessing." },
    { kind: "line", text: "And guessing with cannon is considered rude." },
    { kind: "line", text: "Your garage also carries repair kits, reconnaissance support, researched equipment, your available silver, and your experience." },
    { kind: "line", text: "Use them wisely." },
    { kind: "line", text: "A tank that survives battle may still come home needing repair." },
    { kind: "line", text: "Machines remember abuse." },
    { kind: "line", text: "Mechanics remember it longer." },
    { kind: "line", text: "Now, battle itself." },
    { kind: "line", text: "Select tank." },
    { kind: "line", text: "Select map." },
    { kind: "line", text: "Choose your match." },
    { kind: "line", text: "Make sure your machine is ready." },
    { kind: "line", text: "Then press **Deploy**." },
    { kind: "line", text: "You may fight the range, assemble a squad, or create and join multiplayer lobbies using a code." },
    { kind: "line", text: "Once you are out there, armor angle matters. Position matters. Cover matters. Ammunition matters. Knowing when **not** to fire matters." },
    { kind: "line", text: "A stationary tank is easy target." },
    { kind: "line", text: "A moving tank is harder target." },
    { kind: "line", text: "A moving tank driven by idiot is..." },
    { kind: "sfx", text: "long pause" },
    { kind: "line", text: "still idiot." },
    { kind: "line", text: "But harder to hit." },
    { kind: "line", text: "There is also the **3D Proving Ground** for testing machines in mud, trees, buildings and destruction, and the **Quarry** if you want room to drive, experiment, and learn the terrain without immediately becoming scrap metal." },
    { kind: "line", text: "Use them." },
    { kind: "line", text: "Learn your tank." },
    { kind: "line", text: "Learn its gun." },
    { kind: "line", text: "Learn what it can see." },
    { kind: "line", text: "Learn what can see it." },
    { kind: "line", text: "And remember—" },
    { kind: "sfx", text: "leans closer" },
    { kind: "line", text: "The enemy does not have to destroy whole tank." },
    { kind: "line", text: "He only has to destroy the part containing you." },
    { kind: "sfx", text: "beat" },
    { kind: "sfx", text: "chuckles warmly" },
    { kind: "line", text: "But do not worry." },
    { kind: "line", text: "If something breaks..." },
    { kind: "line", text: "bring it back to garage." },
    { kind: "line", text: "I have hammer." },
    { kind: "sfx", text: "metal clang" },
    { kind: "line", text: "I have bigger hammer." },
    { kind: "sfx", text: "louder metallic crash" },
    { kind: "line", text: "And if necessary..." },
    { kind: "sfx", text: "whispers" },
    { kind: "line", text: "I have **the hammer**." },
    { kind: "sfx", text: "clears throat" },
    { kind: "line", text: "Now go." },
    { kind: "line", text: "Choose your tank." },
    { kind: "line", text: "Choose your battlefield." },
    { kind: "line", text: "And try not to bring it back in several convenient pieces." },
    { kind: "sfx", text: "calling after player" },
    { kind: "line", text: "And if you see smoke—" },
    { kind: "line", text: "that is either engine..." },
    { kind: "line", text: "or feature!" },
    { kind: "line", text: "I will determine when you return." },
    { kind: "sfx", text: "laughs" },
    { kind: "line", text: "**Welcome to RING LAW, Commander.**" },
    { kind: "line", text: "Now deploy." },
  ] satisfies IntroCue[],
} as const;

export function cueWeight(cue: IntroCue): number {
  if (cue.kind === "sfx") return 3;
  return Math.max(5, cue.text.replace(/\*\*/g, "").trim().split(/\s+/).length);
}

export function cueIndexAt(timeSec: number, durationSec: number, cues: readonly IntroCue[]): number {
  if (!cues.length) return 0;
  const weights = cues.map(cueWeight);
  const total = weights.reduce((a, b) => a + b, 0);
  const dur = durationSec > 0 && Number.isFinite(durationSec) ? durationSec : 1;
  const pos = Math.max(0, Math.min(1, timeSec / dur)) * total;
  let acc = 0;
  for (let i = 0; i < weights.length; i++) {
    acc += weights[i];
    if (pos <= acc) return i;
  }
  return cues.length - 1;
}
